name: ci

on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest
    container: ubuntu
    steps:
      - name: Install build environment
        run: |
          apt-get update
          apt-get install -y git curl build-essential pkg-config libssl-dev libudev-dev python3-dev
        env:
          DEBIAN_FRONTEND: noninteractive

      - uses: actions/checkout@v2
        with:
          submodules: true
          ssh-key: ${{ secrets.SSH_KEY }}

      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          components: rustfmt
          default: true

      - uses: actions/cache@v2
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{ runner.os }}-cargo-${{ secrets.CACHE_VERSION }}-${{ hashFiles('**/Cargo.lock') }}

      - name: Install tools
        run: |
          sh -c "$(curl -sSfL https://release.solana.com/v1.8.2/install)"
          echo "$HOME/.cargo/bin:$HOME/.local/share/solana/install/active_release/bin:$PATH" >> $GITHUB_PATH

      - name: cargo check
        uses: actions-rs/cargo@v1
        with:
          command: check

      - name: cargo fmt
        uses: actions-rs/cargo@v1
        with:
          command: fmt
          args: --all -- --check -q

      - name: cargo clippy
        uses: actions-rs/cargo@v1
        with:
          command: clippy

      - name: Run all tests
        uses: actions-rs/cargo@v1
        with:
          command: test
        env:
          RUST_LOG: solana_client::rpc_client=debug
          RUST_BACKTRACE: 1
